### ISSUE TITLE
TV set room checklist

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam-studio#9]
- [ ] Blender: Bigger chairs
- [ ] Make character art bigger, give them a body (except for @dollarone)
- [ ] *(bonus)* Make art each of the 10 themes, make these "theme items" togglable and draggable
- [ ] *(bonus)* Turn the Aurel's big trophies into items
